# Use Node.js LTS version
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the backend code
COPY . .

# Expose the backend port
EXPOSE 8080

# Use nodemon for development
CMD ["nodemon", "index.js"]
