const videos = [
    {
      title: "Learn Socket.IO for Real-time Chat App, private and group chat with Authentication and Middleware",
      category: ["Programming", "Full Stack", "Education"],
      thumbnail: "https://i.ytimg.com/vi/_h7Pc1woq-I/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCmdqbByN_1vRmscr5EKrotG5jYLQ",
      description: "Ready to build your own real-time chat app with private and group chat options? This Socket.IO tutorial will teach you everything you need to know, including authentication and middleware. Get started now!",
      video: "https://www.youtube.com/embed/_h7Pc1woq-I",
      channelName: "6 Pack Programmer",
      handle: "@6packprogrammer",
      avatar: "https://yt3.ggpht.com/8DHXGxqNVJuiT1bnxECydjk4bRfGRCVHuR0MyAxtkjxa0k0PC_uBU-jCOswGnd_5HaTQRHj_eg=s48-c-k-c0x00ffffff-no-rj",
      views: 250000,
      likes: 7000,
      dislikes: 45
    },
    {
      title: "Learn TypeScript in 1 Hour",
      description: "A quick crash course to get started with TypeScript for JavaScript developers.",
      video: "https://www.youtube.com/embed/BCg4U1FzODs",
      thumbnail: "https://i.ytimg.com/vi/BCg4U1FzODs/hqdefault.jpg",
      category: ["TypeScript", "Frontend", "Programming"],
      channelName: "Programming with Mosh",
      handle: "@mosh",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
      views: 320000,
      likes: 9000,
      dislikes: 30
    },
    {
      title: "GraphQL Crash Course",
      description: "Learn GraphQL by building a complete API from scratch.",
      video: "https://www.youtube.com/embed/Y0lDGjwRYKw",
      thumbnail: "https://i.ytimg.com/vi/Y0lDGjwRYKw/hqdefault.jpg",
      category: ["GraphQL", "API", "Full Stack"],
      channelName: "Traversy Media",
      handle: "@traversymedia",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
      views: 210000,
      likes: 7500,
      dislikes: 28
    },
    {
      title: "Docker for Beginners",
      description: "Understand containers and Docker basics to start containerizing apps.",
      video: "https://www.youtube.com/embed/fqMOX6JJhGo",
      thumbnail: "https://i.ytimg.com/vi/fqMOX6JJhGo/hqdefault.jpg",
      category: ["DevOps", "Docker", "Containers"],
      channelName: "TechWorld with Nana",
      handle: "@techworldwithnana",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQh5O0H9Vrc9vCeM5aZmYp3nLzWbN2ZRLbhmE50=s48-c-k-c0x00ffffff-no-rj",
      views: 500000,
      likes: 14000,
      dislikes: 60
    },
    {
      title: "Kubernetes Crash Course",
      description: "Deploy and manage containerized applications at scale using Kubernetes.",
      video: "https://www.youtube.com/embed/X48VuDVv0do",
      thumbnail: "https://i.ytimg.com/vi/X48VuDVv0do/hqdefault.jpg",
      category: ["DevOps", "Kubernetes", "Containers"],
      channelName: "TechWorld with Nana",
      handle: "@techworldwithnana",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQh5O0H9Vrc9vCeM5aZmYp3nLzWbN2ZRLbhmE50=s48-c-k-c0x00ffffff-no-rj",
      views: 470000,
      likes: 13500,
      dislikes: 55
    },
    {
      title: "Next.js Tutorial for Beginners",
      description: "Learn the basics of Next.js and server-side rendering.",
      video: "https://www.youtube.com/embed/mTz0GXj8NN0",
      thumbnail: "https://i.ytimg.com/vi/mTz0GXj8NN0/hqdefault.jpg",
      category: ["Next.js", "React", "Frontend"],
      channelName: "Traversy Media",
      handle: "@traversymedia",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
      views: 260000,
      likes: 8000,
      dislikes: 35
    },
    {
      title: "Redux Toolkit Crash Course",
      description: "Manage React state easily using Redux Toolkit.",
      video: "https://www.youtube.com/embed/poQXNp9ItL4",
      thumbnail: "https://i.ytimg.com/vi/poQXNp9ItL4/hqdefault.jpg",
      category: ["Redux", "React", "Frontend"],
      channelName: "Net Ninja",
      handle: "@netninja",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR-7P5Z2q2Gf43G2Lw8S33OHTXgNZaNQ3nvcbiY=s48-c-k-c0x00ffffff-no-rj",
      views: 190000,
      likes: 6400,
      dislikes: 40
    },
    {
      title: "Git & GitHub Crash Course",
      description: "Learn Git and GitHub essentials for version control and collaboration.",
      video: "https://www.youtube.com/embed/RGOj5yH7evk",
      thumbnail: "https://i.ytimg.com/vi/RGOj5yH7evk/hqdefault.jpg",
      category: ["Git", "Version Control", "Collaboration"],
      channelName: "Traversy Media",
      handle: "@traversymedia",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
      views: 800000,
      likes: 25000,
      dislikes: 90
    },
    {
      title: "Python for Beginners",
      description: "Learn Python programming from scratch with this beginner tutorial.",
      video: "https://www.youtube.com/embed/_uQrJ0TkZlc",
      thumbnail: "https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
      category: ["Python", "Programming", "Backend"],
      channelName: "Programming with Mosh",
      handle: "@mosh",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
      views: 1500000,
      likes: 48000,
      dislikes: 200
    },
    {
      title: "Learn HTML in 1 Hour",
      description: "Quick guide to learning HTML for web development.",
      video: "https://www.youtube.com/embed/pQN-pnXPaVg",
      thumbnail: "https://i.ytimg.com/vi/pQN-pnXPaVg/hqdefault.jpg",
      category: ["HTML", "Frontend", "Web Development"],
      channelName: "Programming with Mosh",
      handle: "@mosh",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
      views: 600000,
      likes: 20000,
      dislikes: 80
    },
    {
      title: "Learn CSS in 1 Hour",
      description: "A complete beginner's guide to CSS and styling websites.",
      video: "https://www.youtube.com/embed/yfoY53QXEnI",
      thumbnail: "https://i.ytimg.com/vi/yfoY53QXEnI/hqdefault.jpg",
      category: ["CSS", "Frontend", "Web Development"],
      channelName: "Traversy Media",
      handle: "@traversymedia",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
      views: 550000,
      likes: 18000,
      dislikes: 70
    },
    {
      title: "Django Crash Course",
      description: "Learn Django framework and build your first web app.",
      video: "https://www.youtube.com/embed/F5mRW0jo-U4",
      thumbnail: "https://i.ytimg.com/vi/F5mRW0jo-U4/hqdefault.jpg",
      category: ["Python", "Django", "Web Development"],
      channelName: "Programming with Mosh",
      handle: "@mosh",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
      views: 430000,
      likes: 14500,
      dislikes: 60
    },
    {
      title: "Angular Crash Course",
      description: "Master Angular framework basics and build scalable apps.",
      video: "https://www.youtube.com/embed/3qBXWUpoPHo",
      thumbnail: "https://i.ytimg.com/vi/3qBXWUpoPHo/hqdefault.jpg",
      category: ["Angular", "Frontend", "Web Development"],
      channelName: "Programming with Mosh",
      handle: "@mosh",
      avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
      views: 370000,
      likes: 13000,
      dislikes: 55
    }
  ];
  
  export default videos;
  