const videos = [

    // UserAjay
    // channelID - 68a060528a0312438d9659ef
    // ownerId - 689f7ba8272ed7688b2d2bc0
    
    //UserRahul 
    // channelID - 68a05f3e8a0312438d9659eb
    // ownerID - 68a05e58a7c77c73e065ee0b
    {
        title: "Learn Socket.IO for Real-time Chat App, private and group chat with Authentication and Middleware",
        category: ["Programming", "Full Stack", "Education"],
        thumbnail: "https://i.ytimg.com/vi/_h7Pc1woq-I/hqdefault.jpg?sqp=-oaymwEnCPYBEIoBSFryq4qpAxkIARUAAIhCGAHYAQHiAQoIGBACGAY4AUAB&rs=AOn4CLCmdqbByN_1vRmscr5EKrotG5jYLQ",
        description: "Ready to build your own real-time chat app with private and group chat options? This Socket.IO tutorial will teach you everything you need to know, including authentication and middleware. Get started now!",
        video: "https://www.youtube.com/embed/_h7Pc1woq-I",
        channelName: "6 Pack Programmer",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@6packprogrammer",
        avatar: "https://yt3.ggpht.com/8DHXGxqNVJuiT1bnxECydjk4bRfGRCVHuR0MyAxtkjxa0k0PC_uBU-jCOswGnd_5HaTQRHj_eg=s48-c-k-c0x00ffffff-no-rj",
        views: 250000,
        likes: 7000,
        dislikes: 45
    },
    {
        title: "Learn TypeScript in 1 Hour",
        description: "A quick crash course to get started with TypeScript for JavaScript developers.",
        video: "https://www.youtube.com/embed/BCg4U1FzODs",
        thumbnail: "https://i.ytimg.com/vi/BCg4U1FzODs/hqdefault.jpg",
        category: ["TypeScript", "Frontend", "Programming"],
        channelName: "Programming with Mosh",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@mosh",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        views: 320000,
        likes: 9000,
        dislikes: 30
    },
    {
        title: "GraphQL Crash Course",
        description: "Learn GraphQL by building a complete API from scratch.",
        video: "https://www.youtube.com/embed/Y0lDGjwRYKw",
        thumbnail: "https://i.ytimg.com/vi/Y0lDGjwRYKw/hqdefault.jpg",
        category: ["GraphQL", "API", "Full Stack"],
        channelName: "Traversy Media",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@traversymedia",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        views: 210000,
        likes: 7500,
        dislikes: 28
    },
    {
        title: "Docker for Beginners",
        description: "Understand containers and Docker basics to start containerizing apps.",
        video: "https://www.youtube.com/embed/fqMOX6JJhGo",
        thumbnail: "https://i.ytimg.com/vi/fqMOX6JJhGo/hqdefault.jpg",
        category: ["DevOps", "Docker", "Containers"],
        channelName: "TechWorld with Nana",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@techworldwithnana",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQh5O0H9Vrc9vCeM5aZmYp3nLzWbN2ZRLbhmE50=s48-c-k-c0x00ffffff-no-rj",
        views: 500000,
        likes: 14000,
        dislikes: 60
    },
    {
        title: "Kubernetes Crash Course",
        description: "Deploy and manage containerized applications at scale using Kubernetes.",
        video: "https://www.youtube.com/embed/X48VuDVv0do",
        thumbnail: "https://i.ytimg.com/vi/X48VuDVv0do/hqdefault.jpg",
        category: ["DevOps", "Kubernetes", "Containers"],
        channelName: "TechWorld with Nana",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@techworldwithnana",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQh5O0H9Vrc9vCeM5aZmYp3nLzWbN2ZRLbhmE50=s48-c-k-c0x00ffffff-no-rj",
        views: 470000,
        likes: 13500,
        dislikes: 55
    },
    {
        title: "Next.js Tutorial for Beginners",
        description: "Learn the basics of Next.js and server-side rendering.",
        video: "https://www.youtube.com/embed/mTz0GXj8NN0",
        thumbnail: "https://i.ytimg.com/vi/mTz0GXj8NN0/hqdefault.jpg",
        category: ["Next.js", "React", "Frontend"],
        channelName: "Traversy Media",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@traversymedia",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        views: 260000,
        likes: 8000,
        dislikes: 35
    },
    {
        title: "Redux Toolkit Crash Course",
        description: "Manage React state easily using Redux Toolkit.",
        video: "https://www.youtube.com/embed/poQXNp9ItL4",
        thumbnail: "https://i.ytimg.com/vi/poQXNp9ItL4/hqdefault.jpg",
        category: ["Redux", "React", "Frontend"],
        channelName: "Net Ninja",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@netninja",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR-7P5Z2q2Gf43G2Lw8S33OHTXgNZaNQ3nvcbiY=s48-c-k-c0x00ffffff-no-rj",
        views: 190000,
        likes: 6400,
        dislikes: 40
    },
    {
        title: "Git & GitHub Crash Course",
        description: "Learn Git and GitHub essentials for version control and collaboration.",
        video: "https://www.youtube.com/embed/RGOj5yH7evk",
        thumbnail: "https://i.ytimg.com/vi/RGOj5yH7evk/hqdefault.jpg",
        category: ["Git", "Version Control", "Collaboration"],
        channelName: "Traversy Media",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@traversymedia",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        views: 800000,
        likes: 25000,
        dislikes: 90
    },
    {
        title: "Python for Beginners",
        description: "Learn Python programming from scratch with this beginner tutorial.",
        video: "https://www.youtube.com/embed/_uQrJ0TkZlc",
        thumbnail: "https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg",
        category: ["Python", "Programming", "Backend"],
        channelName: "Programming with Mosh",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@mosh",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        views: 1500000,
        likes: 48000,
        dislikes: 200
    },
    {
        title: "Learn HTML in 1 Hour",
        description: "Quick guide to learning HTML for web development.",
        video: "https://www.youtube.com/embed/pQN-pnXPaVg",
        thumbnail: "https://i.ytimg.com/vi/pQN-pnXPaVg/hqdefault.jpg",
        category: ["HTML", "Frontend", "Web Development"],
        channelName: "Programming with Mosh",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@mosh",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        views: 600000,
        likes: 20000,
        dislikes: 80
    },
    {
        title: "Learn CSS in 1 Hour",
        description: "A complete beginner's guide to CSS and styling websites.",
        video: "https://www.youtube.com/embed/yfoY53QXEnI",
        thumbnail: "https://i.ytimg.com/vi/yfoY53QXEnI/hqdefault.jpg",
        category: ["CSS", "Frontend", "Web Development"],
        channelName: "Traversy Media",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@traversymedia",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        views: 550000,
        likes: 18000,
        dislikes: 70
    },
    {
        title: "Django Crash Course",
        description: "Learn Django framework and build your first web app.",
        video: "https://www.youtube.com/embed/F5mRW0jo-U4",
        thumbnail: "https://i.ytimg.com/vi/F5mRW0jo-U4/hqdefault.jpg",
        category: ["Python", "Django", "Web Development"],
        channelName: "Programming with Mosh",
        channelId: "68a05f3e8a0312438d9659eb",
        uploader: "68a05e58a7c77c73e065ee0b",
        handle: "@mosh",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        views: 430000,
        likes: 14500,
        dislikes: 60
    },
    {
        title: "Angular Crash Course",
        description: "Master Angular framework basics and build scalable apps.",
        video: "https://www.youtube.com/embed/3qBXWUpoPHo",
        thumbnail: "https://i.ytimg.com/vi/3qBXWUpoPHo/hqdefault.jpg",
        category: ["Angular", "Frontend", "Web Development"],
        channelName: "Programming with Mosh",
        channelId: "68a060528a0312438d9659ef",
        uploader: "689f7ba8272ed7688b2d2bc0",
        handle: "@mosh",
        avatar: "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        views: 370000,
        likes: 13000,
        dislikes: 55
    },
    {
        "title": "React JS Crash Course",
        "description": "Learn React JS from scratch in this beginner-friendly tutorial.",
        "video": "https://www.youtube.com/embed/w7ejDZ8SWv8",
        "thumbnail": "https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg",
        "category": ["React", "Frontend", "Web Development"],
        "channelName": "Traversy Media",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@traversymedia",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        "views": 500000,
        "likes": 15000,
        "dislikes": 120
    },
    {
        "title": "Node.js Crash Course",
        "description": "Get started with Node.js by building simple applications.",
        "video": "https://www.youtube.com/embed/fBNz5xF-Kx4",
        "thumbnail": "https://i.ytimg.com/vi/fBNz5xF-Kx4/hqdefault.jpg",
        "category": ["Backend", "JavaScript", "Node.js"],
        "channelName": "Traversy Media",
        "channelId": "68a060528a0312438d9659ef",
        "uploader": "689f7ba8272ed7688b2d2bc0",
        "handle": "@traversymedia",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        "views": 300000,
        "likes": 10000,
        "dislikes": 80
    },
    {
        "title": "MongoDB Crash Course",
        "description": "Master MongoDB with this detailed crash course.",
        "video": "https://www.youtube.com/embed/Of1sTIH0Yyo",
        "thumbnail": "https://i.ytimg.com/vi/Of1sTIH0Yyo/hqdefault.jpg",
        "category": ["Database", "MongoDB", "NoSQL"],
        "channelName": "Net Ninja",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@netninja",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLR-7P5Z2q2Gf43G2Lw8S33OHTXgNZaNQ3nvcbiY=s48-c-k-c0x00ffffff-no-rj",
        "views": 200000,
        "likes": 8000,
        "dislikes": 50
    },
    {
        "title": "Express.js Crash Course",
        "description": "Learn Express.js to create fast, minimal web servers.",
        "video": "https://www.youtube.com/embed/L72fhGm1tfE",
        "thumbnail": "https://i.ytimg.com/vi/L72fhGm1tfE/hqdefault.jpg",
        "category": ["Backend", "Express.js", "Web Development"],
        "channelName": "Traversy Media",
        "channelId": "68a060528a0312438d9659ef",
        "uploader": "689f7ba8272ed7688b2d2bc0",
        "handle": "@traversymedia",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        "views": 180000,
        "likes": 6000,
        "dislikes": 40
    },
    {
        "title": "JavaScript ES6 Features",
        "description": "Learn the most useful ES6 features for modern JS development.",
        "video": "https://www.youtube.com/embed/NCwa_xi0Uuc",
        "thumbnail": "https://i.ytimg.com/vi/NCwa_xi0Uuc/hqdefault.jpg",
        "category": ["JavaScript", "Frontend", "Programming"],
        "channelName": "Programming with Mosh",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@mosh",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        "views": 450000,
        "likes": 12000,
        "dislikes": 60
    },
    {
        "title": "Full Stack MERN Tutorial",
        "description": "Step-by-step guide to building a MERN stack app.",
        "video": "https://www.youtube.com/embed/7CqJlxBYj-M",
        "thumbnail": "https://i.ytimg.com/vi/7CqJlxBYj-M/hqdefault.jpg",
        "category": ["MERN", "Full Stack", "Web Development"],
        "channelName": "Dev Ed",
        "channelId": "68a060528a0312438d9659ef",
        "uploader": "689f7ba8272ed7688b2d2bc0",
        "handle": "@deved",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLRjEcDZZkgvQTSYvWTh2jYWSbb-tHCM36gK8LqE=s48-c-k-c0x00ffffff-no-rj",
        "views": 600000,
        "likes": 20000,
        "dislikes": 100
    },
    {
        "title": "React Router v6 Tutorial",
        "description": "Learn how to use React Router v6 to navigate your app.",
        "video": "https://www.youtube.com/embed/UjISzqM0sUw",
        "thumbnail": "https://i.ytimg.com/vi/UjISzqM0sUw/hqdefault.jpg",
        "category": ["React", "Frontend", "Routing"],
        "channelName": "Codevolution",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@codevolution",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLRkJNGG8FYFJr0fx6FkVcVgFDP1ElNmijO0s7d1=s48-c-k-c0x00ffffff-no-rj",
        "views": 150000,
        "likes": 5000,
        "dislikes": 25
    },
    {
        "title": "JWT Authentication in Node.js",
        "description": "Secure your Node.js applications using JWT authentication.",
        "video": "https://www.youtube.com/embed/mbsmsi7l3r4",
        "thumbnail": "https://i.ytimg.com/vi/mbsmsi7l3r4/hqdefault.jpg",
        "category": ["Security", "Authentication", "Backend"],
        "channelName": "Academind",
        "channelId": "68a060528a0312438d9659ef",
        "uploader": "689f7ba8272ed7688b2d2bc0",
        "handle": "@academind",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQ8YyO1PHzRSx4RrrgI3cQ6jE1yPf-3OYiEnM7X=s48-c-k-c0x00ffffff-no-rj",
        "views": 220000,
        "likes": 9000,
        "dislikes": 30
    },
    {
        "title": "Tailwind CSS Crash Course",
        "description": "Get started with Tailwind CSS for rapid UI development.",
        "video": "https://www.youtube.com/embed/dFgzHOX84xQ",
        "thumbnail": "https://i.ytimg.com/vi/dFgzHOX84xQ/hqdefault.jpg",
        "category": ["Frontend", "CSS", "Tailwind"],
        "channelName": "Traversy Media",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@traversymedia",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQmR6EYZs4-9dY9m4U4BkhYd-7M64F1Pi5Atv0c=s48-c-k-c0x00ffffff-no-rj",
        "views": 350000,
        "likes": 11000,
        "dislikes": 45
    },
    {
        "title": "Building REST API with Express",
        "description": "Learn to create a REST API using Express.js.",
        "video": "https://www.youtube.com/embed/pKd0Rpw7O48",
        "thumbnail": "https://i.ytimg.com/vi/pKd0Rpw7O48/hqdefault.jpg",
        "category": ["Backend", "API", "Express"],
        "channelName": "Programming with Mosh",
        "channelId": "68a060528a0312438d9659ef",
        "uploader": "689f7ba8272ed7688b2d2bc0",
        "handle": "@mosh",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLR7rtA51GZ-1y1c2bMds5db5X2PV8IMLhsM8IuJ=s48-c-k-c0x00ffffff-no-rj",
        "views": 280000,
        "likes": 8500,
        "dislikes": 35
    },
    {
        "title": "React Hooks Explained",
        "description": "A beginner-friendly guide to understanding React Hooks.",
        "video": "https://www.youtube.com/embed/f687hBjwFcM",
        "thumbnail": "https://i.ytimg.com/vi/f687hBjwFcM/hqdefault.jpg",
        "category": ["React", "Frontend", "Web Development"],
        "channelName": "Web Dev Simplified",
        "channelId": "68a05f3e8a0312438d9659eb",
        "uploader": "68a05e58a7c77c73e065ee0b",
        "handle": "@webdevsimplified",
        "avatar": "https://yt3.ggpht.com/ytc/AKedOLQ_mEKtZekog0uqpU7oA7FjXcQglwDdYOfpPNLZ=s48-c-k-c0x00ffffff-no-rj",
        "views": 400000,
        "likes": 13000,
        "dislikes": 50
    }
];

export default videos;
